/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/contexts/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/hooks/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: "#faf5ff",
          100: "#f3e8ff",
          200: "#e9d5ff",
          300: "#d8b4fe",
          400: "#c084fc",
          500: "#a855f7",
          600: "#9333ea",
          700: "#7c3aed",
          800: "#5b21b6",
          900: "#4c1d95",
          950: "#2e1065",
        },
        trust: {
          50: "#eff6ff",
          100: "#dbeafe",
          200: "#bfdbfe",
          300: "#93c5fd",
          400: "#60a5fa",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          800: "#1e40af",
          900: "#1e3a8a",
          950: "#172554",
          DEFAULT: "var(--trust)",
          foreground: "var(--trust-foreground)",
          subtle: "var(--trust-subtle)",
        },
        neutral: {
          0: "#ffffff",
          25: "#fcfcfd",
          50: "#f8fafc",
          100: "#f1f5f9",
          200: "#e2e8f0",
          300: "#cbd5e1",
          400: "#94a3b8",
          500: "#64748b",
          600: "#475569",
          700: "#334155",
          800: "#1e293b",
          900: "#0f172a",
          950: "#020617",
        },
        background: "var(--background)",
        foreground: "var(--foreground)",
        overlay: "var(--overlay)",
        glass: {
          DEFAULT: "var(--glass)",
          muted: "var(--glass-muted)",
          border: "var(--glass-border)",
          strong: "var(--glass-strong)",
        },
        text: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          tertiary: "var(--text-tertiary)",
          inverse: "var(--text-inverse)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
          subtle: "var(--accent-subtle)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
          container: "var(--primary-container)",
          subtle: "var(--primary-subtle)",
          ring: "var(--primary-ring)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
          container: "var(--secondary-container)",
          subtle: "var(--secondary-subtle)",
        },
        success: {
          DEFAULT: "var(--success)",
          foreground: "var(--success-foreground)",
          container: "var(--success-container)",
          subtle: "var(--success-subtle)",
        },
        warning: {
          DEFAULT: "var(--warning)",
          foreground: "var(--warning-foreground)",
          container: "var(--warning-container)",
          subtle: "var(--warning-subtle)",
        },
        danger: {
          DEFAULT: "var(--danger)",
          foreground: "var(--danger-foreground)",
          container: "var(--danger-container)",
          subtle: "var(--danger-subtle)",
        },
        surface: {
          DEFAULT: "var(--surface)",
          muted: "var(--surface-muted)",
          raised: "var(--surface-raised)",
          sunken: "var(--surface-sunken)",
          overlay: "var(--surface-overlay)",
          inverse: "var(--surface-inverse)",
        },
        border: {
          DEFAULT: "var(--border)",
          subtle: "var(--border-subtle)",
          strong: "var(--border-strong)",
        },
        ring: "var(--ring)",
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
      },
      fontFamily: {
        sans: ["Inter", "Segoe UI", "Helvetica Neue", "Arial", "sans-serif"],
        mono: ["IBM Plex Mono", "Cascadia Code", "Consolas", "monospace"],
      },
      fontSize: {
        h1: ["2.5rem", { lineHeight: "2.875rem", fontWeight: "760", letterSpacing: "-0.02em" }],
        h2: ["2rem", { lineHeight: "2.375rem", fontWeight: "740", letterSpacing: "-0.018em" }],
        h3: ["1.5rem", { lineHeight: "2rem", fontWeight: "720", letterSpacing: "-0.014em" }],
        h4: ["1.25rem", { lineHeight: "1.75rem", fontWeight: "700", letterSpacing: "-0.01em" }],
        h5: ["1rem", { lineHeight: "1.5rem", fontWeight: "700" }],
        h6: ["0.875rem", { lineHeight: "1.25rem", fontWeight: "700" }],
        body: ["0.875rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        caption: ["0.75rem", { lineHeight: "1rem", fontWeight: "500" }],
        "display-lg": ["2.75rem", { lineHeight: "3.25rem", fontWeight: "760", letterSpacing: "-0.02em" }],
        "display-md": ["2.25rem", { lineHeight: "2.75rem", fontWeight: "750", letterSpacing: "-0.018em" }],
        "heading-lg": ["1.5rem", { lineHeight: "2rem", fontWeight: "720", letterSpacing: "-0.012em" }],
        "heading-md": ["1.25rem", { lineHeight: "1.75rem", fontWeight: "700", letterSpacing: "-0.01em" }],
        "heading-sm": ["1rem", { lineHeight: "1.5rem", fontWeight: "700" }],
        label: ["0.75rem", { lineHeight: "1rem", fontWeight: "650", letterSpacing: "0.01em" }],
        micro: ["0.6875rem", { lineHeight: "0.875rem", fontWeight: "650", letterSpacing: "0.025em" }],
      },
      spacing: {
        px: "1px",
        0.5: "0.125rem",
        1.5: "0.375rem",
        2.5: "0.625rem",
        3.5: "0.875rem",
        4.5: "1.125rem",
        5.5: "1.375rem",
        18: "4.5rem",
        22: "5.5rem",
        26: "6.5rem",
        30: "7.5rem",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        "3xl": "var(--radius-3xl)",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        focus: "var(--shadow-focus)",
        card: "var(--shadow-card)",
        floating: "var(--shadow-floating)",
        glow: "var(--shadow-glow)",
      },
      ringColor: {
        DEFAULT: "var(--ring)",
      },
    },
  },
};
